import "~/styles/globals.css";
import { Inter } from "next/font/google";
import Header from "../app/Header/page";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Project Management App",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
